POST http://localhost:8080/api/v1/comment/public/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2NDM3MzIsImV4cCI6MTY1NzY0NzMzMiwiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.bluQ3G2iN9L_6aK2avC8nnUzLg8owep139V7G1yz3X4
Content-Type: application/json

{
  "content": "Comment 3",
  "profileId": 1,
  "videoId":"402880e681f182c30181f1840e2c0000",
  "commentId": 1
}

###update
PUT http://localhost:8080/api/v1/comment/public/update?c=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2NDM3MzIsImV4cCI6MTY1NzY0NzMzMiwiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.bluQ3G2iN9L_6aK2avC8nnUzLg8owep139V7G1yz3X4
Content-Type: application/json

{
  "content": "Comment 2"
}
###delete
DELETE http://localhost:8080/api/v1/comment/public/delete?id=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2NDM3MzIsImV4cCI6MTY1NzY0NzMzMiwiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.bluQ3G2iN9L_6aK2avC8nnUzLg8owep139V7G1yz3X4

###pagination
GET http://localhost:8080/api/v1/comment/adm/pagination?size=5&page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc3MDQ0MjYsImV4cCI6MTY1NzcwODAyNiwiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.1bhcQnT-sFR11-spMKonjNATh5tifaUEQlZ0dPxcezU


###get by video id
GET http://localhost:8080/api/v1/comment/public/video/list?v=402880e681f182c30181f1840e2c0000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc3MDgwNDcsImV4cCI6MTY1NzcxMTY0NywiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.7Sl_WXZMzsqkHtVoHFT5Zmm8-43NvE2Kg6tmJ0Jj6hU

###get reply list by comment id
GET http://localhost:8080/api/v1/comment/public/reply/list?c=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc3MDgwNDcsImV4cCI6MTY1NzcxMTY0NywiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.7Sl_WXZMzsqkHtVoHFT5Zmm8-43NvE2Kg6tmJ0Jj6hU

